### ISSUE TITLE
An illegal memory access was encountered CUDA error

### ISSUE THREAD

**Issue by TimBuckrue** [clarte53/GaussianSplattingVRViewerUnity#34]
Hello,

I am having an issue where my scenes which are exported through PostShot are not loading properly in GaussianSplattingVRViewerUtility. When I attempt to load the scene, I get the message, "An illegal memory access was encountered" and the whole application goes down to about 1 fps until it is restarted.

I never had this issue before when using PostShot scenes, but maybe it has something to do with me recently upgrading to RTX 5000. It seems to be a CUDA related error, and I know that older CUDA stuff can be broken on RTX 5000 series. What's strange though is that the sample scene seems to load and run just fine. Perhaps it has something to do with the size of the scene.

_Specs:
Meta Quest 3 through Virtual Desktop
Nvidia RTX 5090
AMD Ryzen 5 9800X3D
96GB DDR5 6400mt/s
Windows 11_

Is there some sort of log I can upload to help further?

**Comment by L-Aidan** [comment]
I encountered the same issue: I added two PLY files, one works correctly while the other throws this error: ( An illegal memory access was encountered CUDA error).

PICO 4 Ultra through PC streaming
Nvidia RTX 5080

Here are my two PLY files：https://drive.google.com/file/d/12wa0fZP8gpLi34Vl6rm_jsDNM9Acm1bv/view?usp=sharing

**Comment by L-Aidan** [comment]
> Hello,
> 
> I am having an issue where my scenes which are exported through PostShot are not loading properly in GaussianSplattingVRViewerUtility. When I attempt to load the scene, I get the message, "An illegal memory access was encountered" and the whole application goes down to about 1 fps until it is restarted.
> 
> I never had this issue before when using PostShot scenes, but maybe it has something to do with me recently upgrading to RTX 5000. It seems to be a CUDA related error, and I know that older CUDA stuff can be broken on RTX 5000 series. What's strange though is that the sample scene seems to load and run just fine. Perhaps it has something to do with the size of the scene.
> 
> _Specs: Meta Quest 3 through Virtual Desktop Nvidia RTX 5090 AMD Ryzen 5 9800X3D 96GB DDR5 6400mt/s Windows 11_
> 
> Is there some sort of log I can upload to help further?

Hello, have you fixed this problem?

**Comment by Kukuruzoed** [comment]
The guys at PostShot have gotten rid of these three export parameters in the new versions: 
<img width="458" height="141" alt="Image" src="https://github.com/user-attachments/assets/f487baf9-c615-4efe-8f83-800617cd79a5" />

Which is likely the cause of the memory reading issues.

The byte size of a single splat has become smaller, and the code is trying to retrieve splat information from where the file has already ended.

I think the solution here is to recompile the gaussiansplatting.dll with adding right code to exporter. Maybe additional splat structure without theese params

**Comment by Kukuruzoed** [comment]
Fixed this in my fork: https://github.com/Kukuruzoed/GaussianSplattingVRViewerUnity

**Comment by SolatK** [comment]
> Fixed this in my fork: https://github.com/Kukuruzoed/GaussianSplattingVRViewerUnity

I compiled your project and still get this error with https://github.com/apple/ml-sharp this model output splats.

I also have no idea how to work with Unity, but I definitely used your code to build the project, so there is a chance of error on my side.
